From openjdk:8

copy ./target/ssassignment1-0.0.1-SNAPSHOT.jar ssassignment1-0.0.1-SNAPSHOT.jar
copy ./target/ssassignment1userservice-0.0.1-SNAPSHOT.jar ssassignment1userservice-0.0.1-SNAPSHOT.jar
copy ./target/ssassignment1getall-0.0.1-SNAPSHOT.jar ssassignment1getall-0.0.1-SNAPSHOT.jar

CMD ["java","-jar","ssassignment1-0.0.1-SNAPSHOT.jar"]


